<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Challenge-1" data-toc-modified-id="Challenge-1-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Challenge 1</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Import-all-required-libraries" data-toc-modified-id="Import-all-required-libraries-1.0.1"><span class="toc-item-num">1.0.1&nbsp;&nbsp;</span>Import all required libraries</a></span></li><li><span><a href="#Import-data-set" data-toc-modified-id="Import-data-set-1.0.2"><span class="toc-item-num">1.0.2&nbsp;&nbsp;</span>Import data set</a></span></li><li><span><a href="#Print-first-10-rows-of-pokemon" data-toc-modified-id="Print-first-10-rows-of-pokemon-1.0.3"><span class="toc-item-num">1.0.3&nbsp;&nbsp;</span>Print first 10 rows of <code>pokemon</code></a></span></li><li><span><a href="#Obtain-the-distinct-values-across-Type-1-and-Type-2" data-toc-modified-id="Obtain-the-distinct-values-across-Type-1-and-Type-2-1.0.4"><span class="toc-item-num">1.0.4&nbsp;&nbsp;</span>Obtain the distinct values across <code>Type 1</code> and <code>Type 2</code></a></span></li><li><span><a href="#Cleanup-Name-that-contain-&quot;Mega&quot;" data-toc-modified-id="Cleanup-Name-that-contain-&quot;Mega&quot;-1.0.5"><span class="toc-item-num">1.0.5&nbsp;&nbsp;</span>Cleanup <code>Name</code> that contain "Mega"</a></span></li><li><span><a href="#Create-a-new-column-called-A/D-Ratio-whose-value-equals-to-Attack-devided-by-Defense" data-toc-modified-id="Create-a-new-column-called-A/D-Ratio-whose-value-equals-to-Attack-devided-by-Defense-1.0.6"><span class="toc-item-num">1.0.6&nbsp;&nbsp;</span>Create a new column called <code>A/D Ratio</code> whose value equals to <code>Attack</code> devided by <code>Defense</code></a></span></li><li><span><a href="#Identify-the-pokemon-with-the-highest-A/D-Ratio" data-toc-modified-id="Identify-the-pokemon-with-the-highest-A/D-Ratio-1.0.7"><span class="toc-item-num">1.0.7&nbsp;&nbsp;</span>Identify the pokemon with the highest <code>A/D Ratio</code></a></span></li><li><span><a href="#Identify-the-pokemon-with-the-lowest-A/D-Ratio" data-toc-modified-id="Identify-the-pokemon-with-the-lowest-A/D-Ratio-1.0.8"><span class="toc-item-num">1.0.8&nbsp;&nbsp;</span>Identify the pokemon with the lowest A/D Ratio</a></span></li><li><span><a href="#Create-a-new-column-called-Combo-Type-whose-value-combines-Type-1-and-Type-2." data-toc-modified-id="Create-a-new-column-called-Combo-Type-whose-value-combines-Type-1-and-Type-2.-1.0.9"><span class="toc-item-num">1.0.9&nbsp;&nbsp;</span>Create a new column called <code>Combo Type</code> whose value combines <code>Type 1</code> and <code>Type 2</code>.</a></span></li><li><span><a href="#Identify-the-pokemons-whose-A/D-Ratio-are-among-the-top-5" data-toc-modified-id="Identify-the-pokemons-whose-A/D-Ratio-are-among-the-top-5-1.0.10"><span class="toc-item-num">1.0.10&nbsp;&nbsp;</span>Identify the pokemons whose <code>A/D Ratio</code> are among the top 5</a></span></li><li><span><a href="#For-the-5-pokemons-printed-above,-aggregate-Combo-Type-and-use-a-list-to-store-the-unique-values." data-toc-modified-id="For-the-5-pokemons-printed-above,-aggregate-Combo-Type-and-use-a-list-to-store-the-unique-values.-1.0.11"><span class="toc-item-num">1.0.11&nbsp;&nbsp;</span>For the 5 pokemons printed above, aggregate <code>Combo Type</code> and use a list to store the unique values.</a></span></li><li><span><a href="#For-each-of-the-Combo-Type-values-obtained-from-the-previous-question,-calculate-the-mean-scores-of-all-numeric-fields-across-all-pokemons." data-toc-modified-id="For-each-of-the-Combo-Type-values-obtained-from-the-previous-question,-calculate-the-mean-scores-of-all-numeric-fields-across-all-pokemons.-1.0.12"><span class="toc-item-num">1.0.12&nbsp;&nbsp;</span>For each of the <code>Combo Type</code> values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemons.</a></span></li></ul></li></ul></li></ul></div>

# Challenge 1

In this challenge you will be working on **pokemons**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](pokemon.jpg)

Follow the instructions below and enter your code.

### Import all required libraries

In [1]:
# import libraries
import pandas as pd
import numpy as np

### Import data set

Import data set `Pokemon.csv` from the `your-code` directory of this lab. Read the data into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [2]:
# import data set
pokemon=pd.read_csv("Pokemon.csv")

### Print first 10 rows of `pokemon`

In [3]:
# enter your code here
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

### Obtain the distinct values across `Type 1` and `Type 2`

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [22]:
# enter your code here
pokemon_types = pokemon[["Type 1", "Type 2"]].drop_duplicates()
pokemon_types

      Type 1    Type 2
230      Bug      Rock
139    Water       NaN
484    Steel   Psychic
103     Rock    Ground
616     Fire   Psychic
..       ...       ...
527  Psychic  Fighting
797  Psychic     Ghost
316      Bug     Ghost
589   Ground     Steel
798  Psychic      Dark

[154 rows x 2 columns]

### Cleanup `Name` that contain "Mega"

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [23]:
# enter your code here
pokemon["Name"] = pokemon.Name.str.replace(r"(\w*Mega)", "Mega")
pokemon

# test transformed data

pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.04
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False,0.18
484,436,Bronzor,Steel,Psychic,300,57,24,86,24,86,23,4,False,0.28
103,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False,0.28
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False,0.29
189,175,Togepi,Fairy,NaN,245,35,20,65,40,65,20,2,False,0.31
456,411,Bastiodon,Rock,Steel,495,60,52,168,47,138,30,4,False,0.31
751,681,AegislashShield Forme,Steel,Ghost,520,60,50,150,50,150,60,6,False,0.33
323,299,Nosepass,Rock,NaN,375,30,45,135,45,90,30,3,False,0.33
773,703,Carbink,Rock,Fairy,500,50,50,150,50,150,50,6,False,0.33

### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [11]:
# enter your code here
pokemon["A/D Ratio"]=round(pokemon["Attack"]/pokemon["Defense"],2)
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.00
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.50
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.75
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.12
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True,3.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
773,703,Carbink,Rock,Fairy,500,50,50,150,50,150,50,6,False,0.33
103,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False,0.28
323,299,Nosepass,Rock,NaN,375,30,45,135,45,90,30,3,False,0.33
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False,0.18
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.04

### Identify the pokemon with the highest `A/D Ratio`

In [12]:
# enter your code here
pokemon.sort_values("A/D Ratio",ascending=False, inplace=True)
display(pokemon)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.00
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.50
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.75
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.12
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True,3.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False,0.29
484,436,Bronzor,Steel,Psychic,300,57,24,86,24,86,23,4,False,0.28
103,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False,0.28
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False,0.18
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.04

### Identify the pokemon with the lowest A/D Ratio

In [13]:
# enter your code here
pokemon.sort_values("A/D Ratio", inplace=True)
display(pokemon)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.04
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False,0.18
484,436,Bronzor,Steel,Psychic,300,57,24,86,24,86,23,4,False,0.28
103,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False,0.28
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False,0.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True,3.00
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.12
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.75
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.50
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.00

### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [ ]:
# Hacerlo con un apply.lambda?
# Hacerlo mediante funcion def?

### Identify the pokemons whose `A/D Ratio` are among the top 5

In [27]:
# enter your code here
top_5=pokemon.nlargest(5, "A/D Ratio")
top_5

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.00
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.50
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.75
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.12
750,681,AegislashBlade Forme,Steel,Ghost,520,60,150,50,150,50,60,6,False,3.00

### For the 5 pokemons printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemons with the highest `A/D Ratio`.

In [ ]:
# enter your code here

### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemons.

Your output should look like below:

![Aggregate](aggregated-mean.png)

In [ ]:
# enter your code here